# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72403d024a76cbbed6afbcdd12b701a60dc40bb6fe169f11028a60731fea0240034e41422e771cced0d0036f63ea06cea10ea72723fa7a0e463e12ae1e24aff8

test:
  secret_key_base: 521ce88811024e7a95d3e1b0abdcb662459ca54ade28a8182c43315d45ac7c6c4d6123a8fadd3b6ab445b379718d63b33fe57a0b088614e219f04993bcdf08c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
