# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10f7c39407f3984a67d2941d338638a0b075f269fec6438e3ee6a20b301b526c51c9b79ef1bac918b4194c39c86b84ec51a8ffcee9433989e59ab11a4189e4e8

test:
  secret_key_base: 75e72c820ea97c716bcdaf74de58efb6f1f6265412410dd1fd14dd504469837a6345952e9cb13b14c55bd68341bf7d753dc2bb97de3e79585cc43f01fdc4eeda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
